/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.boot.gradle;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class MainApplication {
	
	public static void main(String[] args) {
		System.out.println("Main Application Started..................!!!");
		SpringApplication.run(MainApplication.class, args);
	}
}



// To run:- gradle bootrun