/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.boot.gradle;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainApplicationTest {
    @Test public void testSomeLibraryMethod() {
        MainApplication classUnderTest = new MainApplication();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
